ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

INSERT INTO t_sip_depto VALUES(01, 'FINANCEIRO', 'FIN');
INSERT INTO t_sip_depto VALUES(02, 'TECNOLOGIA DA INFORMAÇÃO', 'TI');

COMMIT;

ALTER TABLE t_sip_projeto RENAME COLUMN dt_inciio TO dt_inicio;

INSERT INTO t_sip_projeto VALUES( 01,'CHALLENGE_01', TO_DATE('05/08/2024', 'DD/MM/YYYY'), TO_DATE('15/10/2024', 'DD/MM/YYYY'));
INSERT INTO t_sip_projeto VALUES( 02,'CHALLENGE_02', TO_DATE('05/08/2024', 'DD/MM/YYYY'), TO_DATE('15/10/2024', 'DD/MM/YYYY'));
INSERT INTO t_sip_projeto VALUES( 03,'CHALLENGE_03', TO_DATE('05/08/2024', 'DD/MM/YYYY'), NULL);

COMMIT;

DESC T_SIP_PROJETO

--COPIAR LINHAS DE UMA TABELA PARA OUTRA

CREATE TABLE T_COPY_STP_PROJETO AS 
SELECT * FROM T_SIP_PROJETO WHERE 1=2;

INSERT INTO T_COPY_SIP_PROJETO  (
    SELECT CD_PROJETO, NM_PROJETO,  DT_INICIO, DT_TERMINO
    FROM t_sip_projeto WHERE DT_TERMINO IS NOT NULL
);

CREATE TABLE T_COPY_SIP_PROJETO AS SELECT * FROM T_SIP_PROJETO WHERE DT_TERMINO IS NOT NULL;

UPDATE T_SIP_PROJETO
SET DT_TERMINO = (SELECT DT_TERMINO FROM T_SIP_PROJETO WHERE CD_PROJETO = 1)
WHERE dt_termino IS NULL;

SELECT * FROM T_SIP_FUNCIONARIO;

DESC T_SIP_FUNCIONARIO;
INSERT INTO T_SIP_FUNCIONARIO VALUES (
    1, 2, 'MARIA', TO_DATE('01/05/1991','DD/MM/YYYY'), 
    TO_DATE('01/05/2001','DD/MM/YYYY'), 5423.30
);
UPDATE T_SIP_FUNCIONARIO
    SET nm_funcionario = 'JOSE',
        DT_NASCIMENTO = TO_DATE('01/02/1965','DD/MM/YYYY')
    WHERE NR_MATRICULA = 1;
UPDATE T_SIP_FUNCIONARIO
    SET vl_salario = 5423.3 * 1.055
    WHERE NR_MATRICULA = 1;

COMMIT;

DELETE FROM T_SIP_FUNCIONARIO WHERE NR_MATRICULA = 1;
